### PR TITLE
Drop df dep

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by davidanthoff** [comment]
Actually, lets wait with a merge for a moment, I have a few more things I want to fix here!

**Comment by davidanthoff** [comment]
Alright, ready for CI and review.

I changed the tests a bit around.

**Comment by bramtayl** [comment]
Maybe it's worth checking in with the SQLite.jl folks before we merge this?

**Comment by davidanthoff** [comment]
I think we can just merge it for now? I'm not too worried about it. I've also been thinking about another strategy for this in general, so I think before we move anything upstream, I'd like to ponder it a bit more.

**Pull request merged**
